"""
Weekly report generation for Open Brain.
Generates markdown reports of memory activity.
"""
import sys
import os
from datetime import datetime, timedelta
from typing import Dict, List, Optional

# Add src to path for imports
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from db import queries
from analytics.trends import TrendAnalyzer


class WeeklyReport:
    """Generate weekly memory reports."""
    
    def __init__(self, days: int = 7):
        self.days = days
        self.analyzer = TrendAnalyzer(weeks=4)
    
    def generate(self) -> str:
        """
        Generate a markdown report for the past week.
        
        Returns:
            Markdown-formatted report
        """
        stats = queries.get_memory_stats()
        memories = queries.get_memories_for_report(self.days)
        
        # Build the report
        report_lines = [
            "# 📊 Open Brain Weekly Report",
            "",
            f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            f"**Period:** Last {self.days} days",
            "",
            "---",
            "",
            "## 📈 Summary",
            "",
        ]
        
        # Summary stats
        report_lines.extend([
            f"- **Total Memories:** {stats['total']}",
            f"- **This Week:** {stats['this_week']}",
            f"- **This Month:** {stats['this_month']}",
            "",
        ])
        
        # Top tags
        if stats.get('top_tags'):
            report_lines.extend([
                "## 🏷️ Top Tags",
                "",
            ])
            for tag, count in list(stats['top_tags'].items())[:10]:
                report_lines.append(f"- `{tag}`: {count}")
            report_lines.append("")
        
        # Sources
        if stats.get('by_source'):
            report_lines.extend([
                "## 📁 Sources",
                "",
            ])
            for source, count in stats['by_source'].items():
                report_lines.append(f"- **{source}**: {count}")
            report_lines.append("")
        
        # Trending
        trending = self.analyzer.get_top_trending(5)
        if trending:
            report_lines.extend([
                "## 🔥 Trending",
                "",
            ])
            for item in trending:
                trend_emoji = "⬆️" if item['trend'] == 'up' else ("⬇️" if item['trend'] == 'down' else "➡️")
                report_lines.append(
                    f"- `{item['tag']}`: {item['current']} ({trend_emoji} {item['change']:+d})"
                )
            report_lines.append("")
        
        # Recent memories
        if memories:
            report_lines.extend([
                "## 📝 Recent Memories",
                "",
            ])
            
            # Group by date
            by_date: Dict[str, List] = {}
            for mem in memories[:20]:  # Last 20
                date_key = mem['created_at'].strftime('%Y-%m-%d')
                if date_key not in by_date:
                    by_date[date_key] = []
                by_date[date_key].append(mem)
            
            for date_key in sorted(by_date.keys(), reverse=True):
                report_lines.append(f"### {date_key}")
                for mem in by_date[date_key]:
                    content_preview = mem['content'][:80] + "..." if len(mem['content']) > 80 else mem['content']
                    tags_str = ", ".join(f"`{t}`" for t in mem.get('tags', [])[:5])
                    report_lines.append(
                        f"- {content_preview} {tags_str}"
                    )
                report_lines.append("")
        
        # Entity highlights
        entity_trends = self.analyzer.get_entity_trends()
        if entity_trends:
            report_lines.extend([
                "## 🔍 Entity Highlights",
                "",
            ])
            
            for entity_type, entities in list(entity_trends.items())[:5]:
                report_lines.append(f"### {entity_type.title()}")
                for name, count in list(entities.items())[:5]:
                    report_lines.append(f"- {name}: {count}")
                report_lines.append("")
        
        # Activity timeline
        timeline = self.analyzer.get_activity_timeline(self.days)
        if timeline:
            report_lines.extend([
                "## 📅 Activity Timeline",
                "",
                "| Date | Count |",
                "|------|-------|",
            ])
            for date_str, count in sorted(timeline.items(), reverse=True)[:7]:
                report_lines.append(f"| {date_str} | {count} |")
            report_lines.append("")
        
        report_lines.append("---")
        report_lines.append("*Generated by Open Brain*")
        
        return "\n".join(report_lines)
    
    def generate_simple(self) -> str:
        """Generate a simpler, shorter report."""
        stats = queries.get_memory_stats()
        memories = queries.get_memories_for_report(self.days)
        
        lines = [
            f"# Weekly Memory Report",
            f"",
            f"Week: {stats['this_week']} | Month: {stats['this_month']} | Total: {stats['total']}",
            "",
        ]
        
        # Top 5 tags
        top_tags = list(stats.get('top_tags', {}).items())[:5]
        if top_tags:
            tags_str = " | ".join([f"{t}:{c}" for t, c in top_tags])
            lines.append(f"Tags: {tags_str}")
        
        # Recent
        if memories:
            lines.append("")
            lines.append("Recent:")
            for mem in memories[:5]:
                preview = mem['content'][:50] + "..." if len(mem['content']) > 50 else mem['content']
                lines.append(f"- {preview}")
        
        return "\n".join(lines)


def generate_weekly_report(days: int = 7) -> str:
    """Convenience function to generate a weekly report."""
    return WeeklyReport(days).generate()


def generate_simple_report(days: int = 7) -> str:
    """Convenience function to generate a simple report."""
    return WeeklyReport(days).generate_simple()
